fix options
git-svn-id: svn+ssh://svn.df7cb.de/svn/dotfiles/cb@2540 fe09b2a2-98fd-0310-b664-c0abd371c07e

diff --git a/bin/dbp b/bin/dbp
--- a/bin/dbp
+++ b/bin/dbp
@@ -2,6 +2,11 @@
 
 set -e
 
+if [ ! -e debian/changelog ]; then
+	echo "debian/changelog not found" >&2
+	exit 1
+fi
+
 ARG="-rfakeroot -us -uc -i -I"
 DIST=$(dpkg-parsechangelog | awk '/^Distribution:/ { print $2 }')
 
@@ -41,14 +46,14 @@ case $DIST in
 esac
 
 if [ "${1:-}" = "-n" ]; then
-    export DEB_BUILD_OPTIONS="${DEB_BUILD_OPTIONS:-} nocheck"
+    export DEB_BUILD_OPTIONS="${DEB_BUILD_OPTIONS:+$DEB_BUILD_OPTIONS }nocheck"
     shift
 else
     export DEB_CHECK_COMMAND="lintian"
 fi
 
 if [ "${1:-}" = "-o" ]; then
-	export DEB_BUILD_OPTIONS="${DEB_BUILD_OPTIONS:-} noopt"
+	export DEB_BUILD_OPTIONS="${DEB_BUILD_OPTIONS:+$DEB_BUILD_OPTIONS }noopt"
 	shift
 fi
 
